POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "coco",
  "idCard": "123457",
  "type": "2"
}

###

GET http://localhost:8000/member/passenger/query-list?page=1&size=2
Accept: application/json
token: {{token}}

###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": 1893271441852469248,
  "memberId": 1,
  "name": "koko",
  "idCard": "123457",
  "type": "2"
}